Style/Documentation:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Metrics/BlockLength:
  Enabled: false